import type { PhoneNumber } from "../types/PhoneNumber.types";

export const MOCK_PHONE_NUMBERS: PhoneNumber[] = [
  {
    id: "pn-1",
    number: "+1 (415) 555-0101",
    friendlyName: "Sales Line",
    country: "United States",
    countryCode: "US",
    provider: "ours",
    status: "active",
    capabilities: ["voice", "sms"],
    assignedAgent: "Sales Qualifier",
    monthlyCallCount: 842,
    createdAt: "2026-01-10",
  },
  {
    id: "pn-2",
    number: "+1 (628) 555-0174",
    friendlyName: "Support Hotline",
    country: "United States",
    countryCode: "US",
    provider: "ours",
    status: "active",
    capabilities: ["voice"],
    assignedAgent: "Support Triage",
    monthlyCallCount: 2_130,
    createdAt: "2026-02-03",
  },
  {
    id: "pn-3",
    number: "+44 20 7946 0831",
    friendlyName: "UK Sales",
    country: "United Kingdom",
    countryCode: "GB",
    provider: "ours",
    status: "active",
    capabilities: ["voice", "sms"],
    assignedAgent: null,
    monthlyCallCount: 310,
    createdAt: "2026-02-18",
  },
  {
    id: "pn-4",
    number: "+33 1 70 61 02 55",
    friendlyName: "France Operations",
    country: "France",
    countryCode: "FR",
    provider: "ours",
    status: "inactive",
    capabilities: ["voice"],
    assignedAgent: null,
    monthlyCallCount: 0,
    createdAt: "2026-03-05",
  },
  {
    id: "pn-5",
    number: "+1 (929) 555-0188",
    friendlyName: "Appointments NY",
    country: "United States",
    countryCode: "US",
    provider: "external",
    status: "active",
    capabilities: ["voice", "sms", "fax"],
    assignedAgent: "Appointment Setter",
    monthlyCallCount: 487,
    createdAt: "2026-03-22",
  },
  {
    id: "pn-6",
    number: "+1 (213) 555-0147",
    friendlyName: "Survey Line",
    country: "United States",
    countryCode: "US",
    provider: "external",
    status: "pending",
    capabilities: ["voice"],
    assignedAgent: null,
    monthlyCallCount: 0,
    createdAt: "2026-04-12",
  },
];
