import type { Agent } from "../types/Agent.types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1",
    name: "Sales Qualifier",
    description: "Qualifies leads via AI and books meetings with the sales team",
    voice: "nova",
    language: "en",
    status: "active",
    avgDuration: "3m 24s",
    successRate: 87,
    createdAt: "2026-03-15",
  },
  {
    id: "agent-2",
    name: "Support Triage",
    description: "Triages support requests and resolves common issues automatically",
    voice: "alloy",
    language: "en",
    status: "active",
    avgDuration: "2m 10s",
    successRate: 92,
    createdAt: "2026-02-28",
  },
  {
    id: "agent-3",
    name: "Appointment Setter",
    description: "Handles appointment scheduling and reminders for clinics",
    voice: "shimmer",
    language: "fr",
    status: "inactive",
    avgDuration: "4m 05s",
    successRate: 78,
    createdAt: "2026-03-01",
  },
  {
    id: "agent-4",
    name: "Survey Collector",
    description: "Conducts post-service satisfaction surveys via voice",
    voice: "echo",
    language: "en",
    status: "draft",
    avgDuration: "—",
    successRate: 0,
    createdAt: "2026-04-10",
  },
];
